# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets/icons/icono.png', 'assets/icons'),
        ('assets/backgrounds/L4D2 BACKGROUND.png', 'assets/backgrounds'),
        ('assets/glows/survivors/ELLIS salud alta.png',
         'assets/glows/survivors'),
        ('assets/glows/survivors/ELLIS salud media.png',
         'assets/glows/survivors'),
        ('assets/glows/survivors/ELLIS VIDA BAJA.png',
         'assets/glows/survivors'),
        ('assets/glows/survivors/ELLIS SALUD CRITICA.png',
         'assets/glows/survivors'),
        ('assets/glows/survivors/COMPAÑEROS DE EQUIPO GLOW.png',
         'assets/glows/survivors'),
        ('assets/glows/survivors/ELLIS INCAPACITADO GLOW.png',
         'assets/glows/survivors'),
        ('assets/glows/survivors/ELLIS GLOW VOMITADO.png',
         'assets/glows/survivors'),
        ('assets/glows/infected/HUNTER glow dominante.png',
         'assets/glows/infected'),
        ('assets/glows/infected/HUNTER dominante glow mask.png',
         'assets/glows/infected'),
        ('assets/glows/infected/HUNTER GLOW INFECTADO ESPECIAL.png',
         'assets/glows/infected'),
        ('assets/glows/infected/GLOW SUPERVIVIENTE VOMITADO COMO INFECTADO.png',
         'assets/glows/infected'),
        ('assets/glows/infected/WICH AGRESVIA GLOW.png',
         'assets/glows/infected'),
        ('assets/glows/infected/WITCH agresiva glow mask.png',
         'assets/glows/infected'),
        ('assets/glows/objects/GLOW ITEMS SIN MESA.png',
         'assets/glows/objects'),
        ('l4d2_core.py', '.'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='L4D2 Mod Loader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets/icons/icon.ico'],
)
